### ISSUE TITLE
Wonder if Assignment 2

### ISSUE THREAD

**Issue by Mr-Wolfram** [Vanditg/COMP-SCI-7059---Artificial-Intelligence#1]
Hello!
Recently, I get in trouble with a problem.by searching in Google, I found that the problem is quite similar to the Assignment 2 in COMP-SCI-7059  . I wonder whether you have finish the Assignment 2. It may give me some idea.
Thank you very much.

**Comment by Vanditg** [comment]
Hi @Mr-Wolfram 
I have started to work on the assignment today and most likely, I'll try to push the solution by 1st May, so you'll have some extra buffer to look at the solution and will get an idea to implement/update your solution. 
Thanks.

**Comment by Mr-Wolfram** [comment]
@Vanditg Thank you so much!

**Comment by Mr-Wolfram** [comment]
@Vanditg Sorry to bother you.
I wonder if you have finished Assignment 2. My problem's deadline is approaching while I didn't make a progress in my problem. 
Thanks again！
