### ISSUE TITLE
Could you please consider taking down these assignment solutions?

### ISSUE THREAD

**Issue by mingyuguo** [Vanditg/COMP-SCI-7059---Artificial-Intelligence#3]
This is Mingyu Guo, I am currently the academic integrity officer of the school of computer science, university of adelaide.

I just met with students who copied code from your github page and submitted as their own.

Could you please consider taking down all these assignments?

**Comment by Vanditg** [comment]
Dear Mingyu, 

Thank you for your issue. 

I have closed this issue and made this repo private.
